### ISSUE TITLE
使用mditor过程中发现的一些问题；

### ISSUE THREAD

**Issue by wteam-xq** [bh-lay/mditor#2]
#### 今天试着使用您这个插件发现的问题如下：
- 1.教程语法错误；
  
  ``` javascript
  //获取textarea dom对象
  var ele_textarea = document.getElementByID('mditor');
  ```
  
  document对象没有“getElementByID”这个方法， 应该写成“getElementById”吧;
- 2.在chrome浏览器中如果按照教程的写法：
  
  ``` javascript
  <textarea id="mditor">……</textarea>
  //获取textarea dom对象
  var ele_textarea = document.getElementById('mditor');
  //实例化Mditor
  var editor = new mditor(ele_textarea);
  ```
  
  会出现“object is not a function”的错误，调试发现是textarea 这个标签id命名成 mditor后， `new mditor`中的`mditor`变成dom节点对象（textarea）了;
- 3.在[编辑器官网](http://bh-lay.github.io/mditor/)点击下载按钮下载的 mditor.js，以上两问题解决后，发现编辑器编辑代码，然后，选择预览时，代码没有灰色背景。（网站demo没问题）

**Comment by bh-lay** [comment]
非常十分以及万分感谢您的反馈，已经确认是我做demo未经测试导致的问题，同时也暴露了自己对ID的一些基础细节掌握尚不完全。
- 1、2 为确实是问题，正在修改中
- 3是为了demo在深色背景展示时，重新修改了`border`、`box-shadow`两部分样式
- 因为编辑器定位为表单内的编辑器，所以原样式仅仅有一条border与浅色背景作区分

再次跪谢您的反馈，小剧感激涕零。
