### ISSUE TITLE
插入内容的时候报错：ReferenceError: me is not defined

### ISSUE THREAD

**Issue by TwoThreeWang** [bh-lay/mditor#9]
大佬，插入内容的时候报错：ReferenceError: me is not defined 怎么处理啊

**Comment by bh-lay** [comment]
抱歉回复这么晚，这个仓库已经不怎么维护了，需要的话可以 fork 一份尝试修复一下，再次抱歉。

**Comment by TwoThreeWang** [comment]
好的，感谢回复
